"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { api } from "../lib/api";
import { MapPin, ArrowRight, Lock, Sparkles, Eye, EyeOff } from "lucide-react";

export default function HubAdminLoginPage() {
  const router = useRouter();
  const [hubIdentifier, setHubIdentifier] = useState("");
  const [password, setPassword] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleLogin = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    setError(null);

    const cleanIdentifier = hubIdentifier.trim();
    if (!cleanIdentifier) {
      setError("Please enter your Hub Phone Number or Hub Code.");
      return;
    }
    if (!password) {
      setError("Please enter your Hub Admin password.");
      return;
    }

    setLoading(true);
    try {
      const user = await api.loginHubAdmin(cleanIdentifier, password);
      if (user) {
        router.push("/");
      }
    } catch (err: any) {
      setError(
        err?.message ||
          "Authentication failed. Please verify your Hub Number and password generated by Super Admin."
      );
    } finally {
      setLoading(false);
    }
  };

  return (
    <div
      style={{
        minHeight: "100vh",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        background: "radial-gradient(circle at 10% 20%, #153A34 0%, #0F2E29 90%)",
        padding: "24px 20px",
        fontFamily: "'Manrope', sans-serif",
      }}
    >
      <div
        style={{
          width: "100%",
          maxWidth: "430px",
          background: "#FFFFFF",
          borderRadius: "18px",
          boxShadow: "0 25px 60px rgba(0, 0, 0, 0.35)",
          padding: "36px 32px",
          position: "relative",
          overflow: "hidden",
        }}
      >
        {/* Top Accent Strip */}
        <div
          style={{
            position: "absolute",
            top: 0,
            left: 0,
            right: 0,
            height: "5px",
            background: "linear-gradient(90deg, #1F4D46, #2E7D5B, #E5623E)",
          }}
        />

        {/* Header Branding */}
        <div style={{ textAlign: "center", marginBottom: "28px" }}>
          <div
            style={{
              display: "inline-flex",
              alignItems: "center",
              justifyContent: "center",
              width: "56px",
              height: "56px",
              borderRadius: "14px",
              background: "#E4ECE9",
              color: "#1F4D46",
              marginBottom: "12px",
            }}
          >
            <MapPin size={28} />
          </div>
          <h1
            style={{
              fontFamily: "'Fraunces', serif",
              fontSize: "26px",
              fontWeight: 700,
              color: "#0F2E29",
              marginBottom: "4px",
            }}
          >
            FreshGo Hub Admin
          </h1>
          <p style={{ fontSize: "13px", color: "#5C6B66", margin: 0 }}>
            Dispatch, Inventory & Delivery Partner Portal
          </p>
        </div>

        {/* Error Alert */}
        {error && (
          <div
            style={{
              padding: "12px 14px",
              borderRadius: "8px",
              background: "#FBE7E3",
              color: "#BE4436",
              fontSize: "13px",
              fontWeight: 600,
              marginBottom: "20px",
            }}
          >
            {error}
          </div>
        )}

        {/* Login Form */}
        <form onSubmit={handleLogin} style={{ display: "grid", gap: "16px" }}>
          <div>
            <label
              style={{
                display: "block",
                fontSize: "11px",
                fontWeight: 700,
                color: "#1F4D46",
                marginBottom: "6px",
                textTransform: "uppercase",
                letterSpacing: "0.5px",
              }}
            >
              Hub Number or Hub Code
            </label>
            <div style={{ position: "relative" }}>
              <MapPin
                size={18}
                style={{
                  position: "absolute",
                  left: "14px",
                  top: "50%",
                  transform: "translateY(-50%)",
                  color: "#8B968F",
                }}
              />
              <input
                type="text"
                value={hubIdentifier}
                onChange={(e) => setHubIdentifier(e.target.value)}
                placeholder="e.g. +919999999999 or HUB-CLT-01"
                required
                style={{
                  width: "100%",
                  padding: "12px 14px 12px 42px",
                  borderRadius: "10px",
                  border: "1px solid #D1D5DB",
                  background: "#F9FAF9",
                  color: "#0F2E29",
                  fontSize: "14px",
                  fontWeight: 600,
                  outline: "none",
                  boxSizing: "border-box",
                }}
              />
            </div>
          </div>

          <div>
            <label
              style={{
                display: "block",
                fontSize: "11px",
                fontWeight: 700,
                color: "#1F4D46",
                marginBottom: "6px",
                textTransform: "uppercase",
                letterSpacing: "0.5px",
              }}
            >
              Hub Admin Password
            </label>
            <div style={{ position: "relative" }}>
              <Lock
                size={18}
                style={{
                  position: "absolute",
                  left: "14px",
                  top: "50%",
                  transform: "translateY(-50%)",
                  color: "#8B968F",
                }}
              />
              <input
                type={showPassword ? "text" : "password"}
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                placeholder="Password generated by Super Admin"
                required
                style={{
                  width: "100%",
                  padding: "12px 42px 12px 42px",
                  borderRadius: "10px",
                  border: "1px solid #D1D5DB",
                  background: "#F9FAF9",
                  color: "#0F2E29",
                  fontSize: "14px",
                  fontWeight: 600,
                  outline: "none",
                  boxSizing: "border-box",
                }}
              />
              <button
                type="button"
                onClick={() => setShowPassword(!showPassword)}
                aria-label={showPassword ? "Hide password" : "Show password"}
                style={{
                  position: "absolute",
                  right: "12px",
                  top: "50%",
                  transform: "translateY(-50%)",
                  background: "transparent",
                  border: "none",
                  color: "#8B968F",
                  cursor: "pointer",
                  display: "grid",
                  placeItems: "center",
                  padding: "4px",
                }}
              >
                {showPassword ? <EyeOff size={18} /> : <Eye size={18} />}
              </button>
            </div>
          </div>

          <button
            type="submit"
            disabled={loading}
            style={{
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              gap: "8px",
              width: "100%",
              padding: "13px",
              borderRadius: "10px",
              background: "#1F4D46",
              color: "#FFFFFF",
              fontSize: "14px",
              fontWeight: 800,
              border: "none",
              cursor: loading ? "not-allowed" : "pointer",
              boxShadow: "0 4px 14px rgba(31, 77, 70, 0.25)",
              marginTop: "4px",
            }}
          >
            {loading ? "Authenticating..." : "Sign In to Hub"}
            <ArrowRight size={16} />
          </button>
        </form>
      </div>
    </div>
  );
}
